### ISSUE TITLE
Famitracker on Mac uses 100% CPU.

### ISSUE THREAD

**Issue by slembcke** [christopherpow/nesicide#37] opened 2019-01-21 16:29 UTC
I sampled the process and found that it's repainting it's UI constantly. Not great for running on battery power with the fans blasting. Haven't tried reproducing the issue on Linux yet.

I was hoping that a fix would be as simple as adding a sleep call somewhere for a few milliseconds, but I've never worked on a Qt project before and am still in the process of getting the dev tools working.

**Comment by slembcke** [comment] 2019-01-25 03:49
The timestamp on the Famitracker app bundle was less than an hour ago, though it still uses 100% CPU. I kind of gave up trying to get the Qt tools working the other day so I'm not much help unfortunately. :-\

**Comment by christopherpow** [comment] 2020-02-19 14:49
Closing as duplicate of issue #60 which will be closed shortly.

**Closed by christopherpow** 2020-02-19 14:49 UTC
