### ISSUE TITLE
100% CPU usage on Windows

### ISSUE THREAD

**Issue by norill** [christopherpow/nesicide#60] opened 2020-02-09 17:13 UTC
Nesicide V2.0.0 uses 100% CPU at all times, it didnt occur with Nesicide V1.007

**Comment by aa-dav** [comment] 2020-02-13 09:20
Indeed, nesicide.exe consumes all time of one CPU core even while emulator is stopped.

**Comment by christopherpow** [comment] 2020-02-13 15:07
I have root caused this to my Qt Famitracker library which is included in nesicide. I don't yet have a fix, short of removing it.

**Comment by christopherpow** [comment] 2020-02-13 17:07
This is a duplicate of https://github.com/christopherpow/nesicide/issues/37

**Comment by christopherpow** [comment] 2020-02-19 15:01
Commit 89d4399bfe44869ccdd1a0510d16eee214bcc16a fixes this.

**Closed by christopherpow** 2020-02-19 15:01 UTC
